---
- hosts: webapps
  tasks:
    - name: Reboot hosts
      shell: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - name: Wait for reboot
      wait_for:
        host: '{{ inventory_hostname }}'
        port: 22
        state: started
        delay: 90
        sleep: 20
      connection: local

    - shell: uptime
